config/routes.rb
Rails.application.routes.draw do
  resources :processos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'processos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/processo.rb
class Processo < ApplicationRecord
    validates :data, :numero, :solicitante, :data_receb, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/processos_controller.rb
class ProcessosController < ApplicationController
  before_action :set_processo, only: [:show, :edit, :update, :destroy]

  # GET /processos
  # GET /processos.json
  def index
    @processos = Processo.all
  end

  # GET /processos/1
  # GET /processos/1.json
  def show
  end

  # GET /processos/new
  def new
    @processo = Processo.new
  end

  # GET /processos/1/edit
  def edit
  end

  # POST /processos
  # POST /processos.json
  def create
    @processo = Processo.new(processo_params)

    respond_to do |format|
      if @processo.save
        format.html { redirect_to @processo, notice: 'Processo was successfully created.' }
        format.json { render :show, status: :created, location: @processo }
      else
        format.html { render :new }
        format.json { render json: @processo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /processos/1
  # PATCH/PUT /processos/1.json
  def update
    respond_to do |format|
      if @processo.update(processo_params)
        format.html { redirect_to @processo, notice: 'Processo was successfully updated.' }
        format.json { render :show, status: :ok, location: @processo }
      else
        format.html { render :edit }
        format.json { render json: @processo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /processos/1
  # DELETE /processos/1.json
  def destroy
    @processo.destroy
    respond_to do |format|
      format.html { redirect_to processos_url, notice: 'Processo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_processo
      @processo = Processo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def processo_params
      params.require(:processo).permit(:numero, :data, :solicitante, :data_receb)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/processos_helper.rb
module ProcessosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ControleProcessos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
</head>
<body style="background-color:#ffffff;">
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="http://intranet.seas.ce.gov.br/intranet/">SEAS</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="/processos">Página inicial<span class="sr-only">(current)</span></a>
        </li>
        <!--
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#">Lista</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        -->
      </ul>
    </div>
  </nav>
  <div style='margin: 33px;'>
    <%= yield %>
  </div>
</body>
</html>

app/views/processos/_form.html.erb
<script>
  $(document).ready(function(){
    $('#processo_numero').mask('9-9');
  });
</script>
<%= form_with(model: processo, local: true) do |form| %>
  <% if processo.errors.any? %>
    <div id="error_explanation">
      <%# <h2>= pluralize(processo.errors.count, "error") prohibited this processo from being saved:</h2> %>
      <ul>
        <% if processo.errors.full_messages %>
          <div class="alert alert-danger" role="alert">
            <li>Todos os campos devem ser preenchidos.<%#= message %></li>
          </div>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-2">
      <%= form.label :numero, "Número do processo" %>
      <%= form.text_field :numero, placeholder: "Ex: 2477487/2018", class: "form-control" %>
    </div>
  </div>
  <br/>
  <div class="row">
    <div class="col-md-2">
      <%= form.label :data, "Data" %>
      <%= form.text_field :data, placeholder: "99/99/9999", class: "form-control" %>
    </div>
  </div>
  <br/>
  <div class="row">
    <div class="col-md-4">
      <%= form.label :solicitante, "Solicitante"%>
      <%= form.text_field :solicitante, placeholder:"Ex: Jailson Mendes", class: "form-control" %>
    </div>
  </div>
  <br/>
  <div class="row">
    <div class="col-md-2">
      <%= form.label :data_receb, "Data de recebimento" %>
      <%= form.text_field :data_receb, placeholder: "99/99/9999", class: "form-control" %>
    </div>
  </div>
  <br/>
  <div class="actions">
    <%= form.submit "Salvar", class: 'btn btn-outline-success'  %>
  </div>
  <br/>
<% end %>

app/views/processos/edit.html.erb
<h1>Editando processo</h1>
<%= render 'form', processo: @processo %>
<br/>
<div class="btn-group">
    <%= link_to 'Mostrar', @processo, class: 'btn btn-secondary btn-outline-dark' %>
    <%= link_to 'Voltar', processos_path, class: 'btn btn-secondary btn-outline-danger' %>
</div>

app/views/processos/index.html.erb
<p id="notice"><%= notice %></p>
<body style="background-color:#ffffff;">
<h1>Processos</h1>
<table class="table table-dark";>
  <thead>
    <tr>
      <th>Número</th>
      <th>Data</th>
      <th>Solicitante</th>
      <th>Data de recebimento</th>
      <th colspan="3">Opções</th>
    </tr>
  </thead>

  <tbody>
    <% @processos.each do |processo| %>
      <tr>
        <td><%= processo.numero %></td>
        <td><%= processo.data %></td>
        <td><%= processo.solicitante %></td>
        <td><%= processo.data_receb %></td>
        <td><%= link_to 'Mostrar', processo, style:"color: " %></td>
        <td><%= link_to 'Editar', edit_processo_path(processo) %></td>
        <td><%= link_to 'Deletar', processo, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Criar novo processo', new_processo_path, class:'btn btn-outline-success' %>

app/views/processos/new.html.erb
<h1>Novo Processo</h1>
<%= render 'form', processo: @processo %>

<%= link_to 'Voltar', processos_path, class:'btn btn-outline-danger' %>

app/views/processos/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Número:</strong>
  <%= @processo.numero %>
</p>

<p>
  <strong>Data:</strong>
  <%= @processo.data %>
</p>

<p>
  <strong>Solicitante:</strong>
  <%= @processo.solicitante %>
</p>

<p>
  <strong>Data de recebimento:</strong>
  <%= @processo.data_receb %>
</p>
<div class="btn group">
<%= link_to 'Editar', edit_processo_path(@processo), class: 'btn btn-secondary btn-outline-dark' %> |
<%= link_to 'Voltar', processos_path, class: 'btn btn-secondary btn-outline-danger' %>
</div>